import os
import asyncio
import json
import logging
import re
from typing import Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv, find_dotenv

# Load env variables from parent folder or current folder
load_dotenv(find_dotenv())

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Initialize FastAPI app
app = FastAPI(
    title="Prompt A/B Testing Dashboard API",
    description="Backend for running A/B experiments on Groq, scoring with a judge LLM, logging to Supabase, and promoting to Llama 3.3 70B via OpenRouter.",
    version="2.0"
)

# CORS configuration to allow access from Streamlit UI
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Retrieve settings
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.1-8b-instant")
PROMOTE_MODEL = os.getenv("PROMOTE_MODEL", "meta-llama/llama-3.3-70b-instruct:free")

# Validate environment setup
if not all([GROQ_API_KEY, OPENROUTER_API_KEY, SUPABASE_URL, SUPABASE_KEY]):
    logger.warning("One or more environment variables are missing! Ensure GROQ_API_KEY, OPENROUTER_API_KEY, SUPABASE_URL, and SUPABASE_KEY are defined.")

# Initialize Supabase client
from supabase import create_client, Client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Initialize LangChain models
from langchain_groq import ChatGroq
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# Groq client for rapid A/B runs and judging
chat_groq = ChatGroq(
    model=GROQ_MODEL,
    groq_api_key=GROQ_API_KEY
)

# Note: OpenRouter client is created dynamically in /api/promote
# to support model selection from the frontend.

# Request schemas
class RunRequest(BaseModel):
    prompt_a: str
    prompt_b: str
    prompt_c: str
    query: str

class PromoteRequest(BaseModel):
    log_id: Optional[str] = None
    winning_prompt: str
    query: str
    model: Optional[str] = None

# Judge LLM scoring template
JUDGE_PROMPT_TEMPLATE = """You are an objective AI evaluator. Your job is to assess three different LLM responses (A, B, and C) to the same user query.
Rate each response on a scale of 1 to 10 based on Clarity, Conciseness, and Helpfulness.
Provide a total score out of 10 for each response, along with a brief, high-quality reason explaining your scoring.

Query:
{query}

Response A (Generated by Prompt A: "{prompt_a}"):
{response_a}

Response B (Generated by Prompt B: "{prompt_b}"):
{response_b}

Response C (Generated by Prompt C: "{prompt_c}"):
{response_c}

Your output MUST be a valid JSON object matching the exact structure below. Do not output anything else. Do not wrap it in standard markdown code block formatting (like ```json). Just the raw JSON:
{{
  "A": {{
    "score": <float between 1.0 and 10.0>,
    "reason": "<brief reasoning>"
  }},
  "B": {{
    "score": <float between 1.0 and 10.0>,
    "reason": "<brief reasoning>"
  }},
  "C": {{
    "score": <float between 1.0 and 10.0>,
    "reason": "<brief reasoning>"
  }}
}}
"""

def parse_json_safely(text: str):
    """
    Cleans and parses JSON response from the LLM Judge.
    Supports raw JSON and markdown JSON code blocks.
    """
    text = text.strip()
    
    # Try parsing directly
    try:
        return json.loads(text)
    except Exception:
        pass

    # Remove Markdown block format if exists
    try:
        cleaned = text
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()
        return json.loads(cleaned)
    except Exception:
        pass

    # Extract JSON block using regex if there's surrounding text
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except Exception as e:
            logger.error(f"Regex extraction JSON parsing failed: {e}")
            
    raise ValueError(f"Could not parse judge response as JSON: {text}")

def _escape_braces(text: str) -> str:
    """Escape curly braces in user text so LangChain doesn't treat them as template variables."""
    return text.replace("{", "{{").replace("}", "}}")

async def run_prompt_variant(prompt_text: str, query_text: str) -> str:
    """Runs a single prompt variant against the user query on Groq."""
    safe_prompt = _escape_braces(prompt_text)
    prompt_template = ChatPromptTemplate.from_messages([
        ("system", safe_prompt),
        ("human", "{query}")
    ])
    chain = prompt_template | chat_groq | StrOutputParser()
    return await chain.ainvoke({"query": query_text})

@app.get("/")
def health_check():
    return {"status": "ok", "message": "Prompt A/B Testing Dashboard API is running."}

@app.post("/api/run")
async def run_ab_test(req: RunRequest):
    logger.info("Received /api/run request.")
    
    try:
        # Run all three variants on Groq simultaneously
        response_a, response_b, response_c = await asyncio.gather(
            run_prompt_variant(req.prompt_a, req.query),
            run_prompt_variant(req.prompt_b, req.query),
            run_prompt_variant(req.prompt_c, req.query)
        )
    except Exception as e:
        logger.error(f"Error calling Groq: {e}")
        raise HTTPException(status_code=500, detail=f"Groq API call failed: {str(e)}")

    # Score each response using a judge LLM on Groq
    try:
        judge_prompt = JUDGE_PROMPT_TEMPLATE.format(
            query=req.query,
            prompt_a=req.prompt_a,
            response_a=response_a,
            prompt_b=req.prompt_b,
            response_b=response_b,
            prompt_c=req.prompt_c,
            response_c=response_c
        )
        
        judge_chain = ChatPromptTemplate.from_messages([
            ("system", "You are a precise JSON-only evaluator. Return only raw JSON, no explanations, no wrappers."),
            ("human", "{eval_text}")
        ]) | chat_groq | StrOutputParser()
        
        judge_response = await judge_chain.ainvoke({"eval_text": judge_prompt})
        evaluation = parse_json_safely(judge_response)
        
        score_a = float(evaluation.get("A", {}).get("score", 5.0))
        reason_a = evaluation.get("A", {}).get("reason", "No reason provided.")
        
        score_b = float(evaluation.get("B", {}).get("score", 5.0))
        reason_b = evaluation.get("B", {}).get("reason", "No reason provided.")
        
        score_c = float(evaluation.get("C", {}).get("score", 5.0))
        reason_c = evaluation.get("C", {}).get("reason", "No reason provided.")
    except Exception as e:
        logger.error(f"Error during Judge LLM evaluation or parsing: {e}")
        # Fail-safe scores
        score_a, reason_a = 5.0, "Parsing failed. Default score applied."
        score_b, reason_b = 5.0, "Parsing failed. Default score applied."
        score_c, reason_c = 5.0, "Parsing failed. Default score applied."

    # Determine winner
    scores = {"A": score_a, "B": score_b, "C": score_c}
    winner = max(scores, key=scores.get)
    winning_prompt = req.prompt_a if winner == "A" else (req.prompt_b if winner == "B" else req.prompt_c)

    # Log the runs to Supabase
    log_id = None
    try:
        db_res = supabase.table("ab_logs").insert({
            "prompt_a": req.prompt_a,
            "prompt_b": req.prompt_b,
            "prompt_c": req.prompt_c,
            "query": req.query,
            "response_a": response_a,
            "response_b": response_b,
            "response_c": response_c,
            "score_a": score_a,
            "score_b": score_b,
            "score_c": score_c,
            "winner": winner
        }).execute()
        
        if db_res.data:
            log_id = db_res.data[0]["id"]
            logger.info(f"Successfully logged run to Supabase with ID: {log_id}")
    except Exception as e:
        logger.error(f"Error inserting log to Supabase: {e}")

    return {
        "log_id": log_id,
        "results": [
            { "variant": "A", "prompt": req.prompt_a, "response": response_a, "score": score_a, "reason": reason_a },
            { "variant": "B", "prompt": req.prompt_b, "response": response_b, "score": score_b, "reason": reason_b },
            { "variant": "C", "prompt": req.prompt_c, "response": response_c, "score": score_c, "reason": reason_c }
        ],
        "winner": winner,
        "winning_prompt": winning_prompt
    }

@app.post("/api/promote")
async def promote_winner(req: PromoteRequest):
    logger.info(f"Received /api/promote request for log_id: {req.log_id}")
    
    # Use selected model or fallback to default
    selected_model = req.model or PROMOTE_MODEL
    logger.info(f"Promoting using model: {selected_model}")
    
    try:
        # Dynamically create OpenRouter chat client for the selected model
        chat_model = ChatOpenAI(
            model=selected_model,
            base_url="https://openrouter.ai/api/v1",
            api_key=OPENROUTER_API_KEY
        )
        
        safe_prompt = _escape_braces(req.winning_prompt)
        prompt_template = ChatPromptTemplate.from_messages([
            ("system", safe_prompt),
            ("human", "{query}")
        ])
        chain = prompt_template | chat_model | StrOutputParser()
        
        final_output = await chain.ainvoke({"query": req.query})
    except Exception as e:
        logger.error(f"Error calling OpenRouter: {e}")
        raise HTTPException(status_code=500, detail=f"OpenRouter API call failed: {str(e)}")

    # Update database log with the final output
    if req.log_id:
        try:
            supabase.table("ab_logs").update({
                "final_output": final_output
            }).eq("id", req.log_id).execute()
            logger.info(f"Updated log {req.log_id} with final output from OpenRouter.")
        except Exception as e:
            logger.error(f"Error updating Supabase with final output: {e}")

    return {
        "model": selected_model,
        "final_output": final_output
    }

@app.get("/api/logs")
def get_logs():
    try:
        db_res = supabase.table("ab_logs").select("*").order("created_at", desc=True).limit(50).execute()
        return db_res.data
    except Exception as e:
        logger.error(f"Error fetching logs from Supabase: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to fetch logs: {str(e)}")
