"""
Scorer — Handles scoring strategy switching between Judge LLM and ML model.

Controlled by SCORER environment variable:
  SCORER=judge  → Full judge LLM scoring (Phase 1)
  SCORER=ml     → Random Forest model + Groq 1-sentence explanation (Phase 2)
  SCORER=auto   → ML if model exists, fallback to judge LLM

Returns same { score, reason } format regardless of mode.
"""

import os
import json
import re
import logging
import joblib
import numpy as np
from pathlib import Path

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

from feature_extractor import extract_features, features_to_vector, FEATURE_NAMES

logger = logging.getLogger(__name__)

# Paths
MODEL_DIR = Path(__file__).parent.parent / "models"
MODEL_PATH = MODEL_DIR / "scorer.pkl"

# Scorer mode from env
SCORER_MODE = os.getenv("SCORER", "auto").lower()

# Cached model reference
_cached_model = None
_model_loaded = False


def _get_groq_client():
    """Create a Groq chat client for scoring/explaining."""
    return ChatGroq(
        model=os.getenv("GROQ_MODEL", "llama-3.1-8b-instant"),
        groq_api_key=os.getenv("GROQ_API_KEY"),
    )


def load_model():
    """Load the Random Forest model from disk. Returns None if not found."""
    global _cached_model, _model_loaded

    if _model_loaded:
        return _cached_model

    if MODEL_PATH.exists():
        try:
            _cached_model = joblib.load(MODEL_PATH)
            _model_loaded = True
            logger.info(f"ML model loaded from {MODEL_PATH}")
            return _cached_model
        except Exception as e:
            logger.error(f"Failed to load model from {MODEL_PATH}: {e}")
            _cached_model = None
            _model_loaded = True
            return None
    else:
        logger.info(f"No model found at {MODEL_PATH}")
        _cached_model = None
        _model_loaded = True
        return None


def reload_model():
    """Force reload the model (called after training or download)."""
    global _cached_model, _model_loaded
    _cached_model = None
    _model_loaded = False
    return load_model()


def model_exists() -> bool:
    """Check if a trained model file exists."""
    return MODEL_PATH.exists()


def get_scorer_mode() -> str:
    """Return the effective scoring mode: 'judge', 'ml', or 'auto'."""
    return SCORER_MODE


def get_active_scorer() -> str:
    """Return what scorer is actually being used right now."""
    if SCORER_MODE == "ml":
        return "ml" if model_exists() else "ml (no model — fallback to judge)"
    elif SCORER_MODE == "judge":
        return "judge"
    else:  # auto
        return "ml" if model_exists() else "judge"


# ---------------------------------------------------------------------------
# Judge LLM scoring (Phase 1)
# ---------------------------------------------------------------------------

JUDGE_PROMPT_TEMPLATE = """You are an objective AI evaluator. Your job is to assess three different LLM responses (A, B, and C) to the same user query.
Rate each response on a scale of 1 to 10 based on Clarity, Conciseness, and Helpfulness.
Provide a total score out of 10 for each response, along with a brief, high-quality reason explaining your scoring.

Query:
{query}

Response A (Generated by Prompt A: "{prompt_a}"):
{response_a}

Response B (Generated by Prompt B: "{prompt_b}"):
{response_b}

Response C (Generated by Prompt C: "{prompt_c}"):
{response_c}

Your output MUST be a valid JSON object matching the exact structure below. Do not output anything else. Do not wrap it in standard markdown code block formatting (like ```json). Just the raw JSON:
{{
  "A": {{
    "score": <float between 1.0 and 10.0>,
    "reason": "<brief reasoning>"
  }},
  "B": {{
    "score": <float between 1.0 and 10.0>,
    "reason": "<brief reasoning>"
  }},
  "C": {{
    "score": <float between 1.0 and 10.0>,
    "reason": "<brief reasoning>"
  }}
}}
"""


def _parse_json_safely(text: str):
    """Clean and parse JSON from LLM judge response."""
    text = text.strip()

    # Try direct parse
    try:
        return json.loads(text)
    except Exception:
        pass

    # Remove markdown code block wrappers
    try:
        cleaned = text
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()
        return json.loads(cleaned)
    except Exception:
        pass

    # Regex extraction
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except Exception as e:
            logger.error(f"Regex extraction JSON parsing failed: {e}")

    raise ValueError(f"Could not parse judge response as JSON: {text}")


async def score_with_judge(
    query: str,
    prompt_a: str, response_a: str,
    prompt_b: str, response_b: str,
    prompt_c: str, response_c: str,
) -> list[dict]:
    """Score 3 responses using the judge LLM. Returns list of {score, reason}."""
    chat_groq = _get_groq_client()

    judge_prompt = JUDGE_PROMPT_TEMPLATE.format(
        query=query,
        prompt_a=prompt_a, response_a=response_a,
        prompt_b=prompt_b, response_b=response_b,
        prompt_c=prompt_c, response_c=response_c,
    )

    judge_chain = ChatPromptTemplate.from_messages([
        ("system", "You are a precise JSON-only evaluator. Return only raw JSON, no explanations, no wrappers."),
        ("human", "{eval_text}")
    ]) | chat_groq | StrOutputParser()

    try:
        judge_response = await judge_chain.ainvoke({"eval_text": judge_prompt})
        evaluation = _parse_json_safely(judge_response)

        results = []
        for variant in ["A", "B", "C"]:
            results.append({
                "score": float(evaluation.get(variant, {}).get("score", 5.0)),
                "reason": evaluation.get(variant, {}).get("reason", "No reason provided."),
            })
        return results
    except Exception as e:
        logger.error(f"Judge LLM scoring failed: {e}")
        return [
            {"score": 5.0, "reason": "Scoring failed. Default score applied."},
            {"score": 5.0, "reason": "Scoring failed. Default score applied."},
            {"score": 5.0, "reason": "Scoring failed. Default score applied."},
        ]


# ---------------------------------------------------------------------------
# ML Model scoring (Phase 2)
# ---------------------------------------------------------------------------

EXPLAIN_PROMPT = """This response scored {score}/10.
Word count: {word_count}, Sentences: {sentence_count}, Avg sentence length: {avg_sent_length} words.
Has bullet points: {has_bullets}. Readability (Flesch): {readability}.
Write one sentence explaining why this score is justified."""


async def _explain_single_variant(chat_groq, variant_label: str, predicted_score: float, features: dict) -> str:
    """Generate 1-sentence explanation from Groq asynchronously with timeout."""
    try:
        explain_text = EXPLAIN_PROMPT.format(
            score=predicted_score,
            word_count=features["word_count"],
            sentence_count=features["sentence_count"],
            avg_sent_length=features["avg_sent_length"],
            has_bullets="Yes" if features["has_bullets"] else "No",
            readability=features["readability"],
        )
        explain_chain = ChatPromptTemplate.from_messages([
            ("system", "You are a concise evaluator. Respond with exactly one sentence."),
            ("human", "{text}")
        ]) | chat_groq | StrOutputParser()

        # Set a tight timeout (3 seconds) for the explanation so evaluation is fast
        reason = await asyncio.wait_for(explain_chain.ainvoke({"text": explain_text}), timeout=3.0)
        return reason.strip()
    except Exception as e:
        logger.warning(f"Groq explanation skipped/timed out for variant {variant_label}: {e}")
        return f"ML model predicted score {predicted_score}/10 based on text features."


async def score_with_ml(
    query: str,
    prompt_a: str, response_a: str,
    prompt_b: str, response_b: str,
    prompt_c: str, response_c: str,
) -> list[dict]:
    """Score 3 responses using the trained ML model + concurrent Groq explanations."""
    model = load_model()
    if model is None:
        logger.warning("ML model not found, falling back to judge LLM")
        return await score_with_judge(
            query, prompt_a, response_a, prompt_b, response_b, prompt_c, response_c
        )

    chat_groq = _get_groq_client()
    variants = [
        ("A", prompt_a, response_a),
        ("B", prompt_b, response_b),
        ("C", prompt_c, response_c),
    ]

    # Extract features & predict scores instantly for all 3 variants
    predicted_scores = []
    features_list = []

    for variant_label, prompt, response in variants:
        features = extract_features(response, prompt, query)
        features_list.append(features)

        feature_vector = np.array([features_to_vector(features)])
        raw_score = float(model.predict(feature_vector)[0])
        predicted_score = round(max(1.0, min(10.0, raw_score)), 1)
        predicted_scores.append(predicted_score)

    # Run all 3 Groq explanation tasks concurrently in parallel
    explain_tasks = [
        _explain_single_variant(chat_groq, var_label, score, feats)
        for (var_label, _, _), score, feats in zip(variants, predicted_scores, features_list)
    ]
    reasons = await asyncio.gather(*explain_tasks)

    return [
        {"score": score, "reason": reason}
        for score, reason in zip(predicted_scores, reasons)
    ]


# ---------------------------------------------------------------------------
# Unified scoring interface
# ---------------------------------------------------------------------------

async def score_responses(
    query: str,
    prompt_a: str, response_a: str,
    prompt_b: str, response_b: str,
    prompt_c: str, response_c: str,
) -> tuple[list[dict], str]:
    """
    Score 3 responses using the configured scoring mode.

    Returns:
        (scores_list, scorer_used)
        scores_list: [{score, reason}, {score, reason}, {score, reason}]
        scorer_used: 'judge' or 'ml'
    """
    use_ml = False

    if SCORER_MODE == "ml":
        use_ml = True
    elif SCORER_MODE == "auto":
        use_ml = model_exists()
    # else: SCORER_MODE == "judge" → use_ml stays False

    if use_ml:
        scores = await score_with_ml(
            query, prompt_a, response_a, prompt_b, response_b, prompt_c, response_c
        )
        scorer_used = "ml"
    else:
        scores = await score_with_judge(
            query, prompt_a, response_a, prompt_b, response_b, prompt_c, response_c
        )
        scorer_used = "judge"

    return scores, scorer_used
